import React, { useState } from "react";
import { Link } from "react-router-dom";
import { ImageWithFallback } from '../components/figma/ImageWithFallback';
import { VideoPlayer, PortfolioVideo } from '../components/VideoPlayer';
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { BackButton } from "../components/BackButton";
import { MEDIA, FALLBACK_MEDIA } from '../components/ImageConfig';
